[package]
name = "steering"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[dependencies]
async-std = { version = "*", features = ["unstable"] }
gilrs = "*"
